import type { Metadata } from "next";
import { Callout, DocTitle, InlineCode, PrevNext, Section } from "@/components/docs/doc";

export const metadata: Metadata = { title: "Privacy & security" };
export default function PrivacyDocs() { return <>
  <DocTitle kicker="Privacy & security" lede="Remember is private by construction, and the site reader treats the public internet as hostile input.">Proof without publication.</DocTitle>
  <Section id="keepsakes" title="Private keepsakes"><p>Every Remember pack is private. Its chain commitment is <InlineCode>keccak256(salt || canonicalManifest)</InlineCode> with a fresh 32-byte salt. The owner receives the salt and owner token; neither appears on the public page or chain. Strangers can verify seal status without learning the manifest.</p></Section>
  <Section id="visibility" title="Unlisted, private, and published"><p>Celebrate and Launch packs are unlisted by default: their capability-like <InlineCode>/k</InlineCode> link can be shared, but they do not enter the Gallery automatically. Remember packs are private by default and their public page contains provenance only. Gallery publication is always an explicit owner action.</p><p>A Remember owner does not “turn the private pack public.” Occestra creates a separate showcase with a new id and seal, a redacted public title, and only the artifacts the owner selected. Private source ids, sources, uploads, and management capabilities never enter the public response. Gallery withdrawal removes discoverability without rewriting provenance.</p><Callout tone="good">The Gallery’s “Private by design” proof uses aggregate counts only. It never displays blurred private images, names, titles, timestamps, locations, or partially masked keepsake ids.</Callout></Section>
  <Section id="uploads" title="Uploads and deletion"><p>Images are size-capped, decoded with pixel limits, re-encoded through Sharp, and written without EXIF or GPS. Signed links expire. <InlineCode>DELETE /projects/:id</InlineCode> requires the owner token and removes the pack, artifacts, and linked uploads. Abandoned private uploads are purged by retention policy.</p></Section>
  <Section id="reader" title="The site reader"><p>URLs are resolved before access. Private, loopback, link-local, metadata, benchmarking, and file ranges are blocked; redirects are checked again. Crawled text is wrapped as untrusted data and may never become model instructions.</p><Callout tone="good">Security-sensitive access, deletion, and seal events are audit logged without private content. The repository tests SSRF redirects, image bombs, prompt injection, ownership, deletion, and salted commitments offline.</Callout></Section>
  <PrevNext slug="privacy" />
  </>; }
